apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Database Hosts
  POSTGRES_HOST: "postgres.default.svc.cluster.local"
  REDIS_HOST: "redis.default.svc.cluster.local:6379"
  
  # Service Endpoints
  AUTH_SVC_ADDR: "auth-service:50051"
  INVENTORY_SVC_ADDR: "inventory-service:50052"
  ORDER_SVC_ADDR: "order-service:50053"
  NOTIFICATION_SVC_ADDR: "notification-service:8080"
